#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSieuThi")]
	public partial class DataDiagramDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTiet_HoaDon_BanHang(ChiTiet_HoaDon_BanHang instance);
    partial void UpdateChiTiet_HoaDon_BanHang(ChiTiet_HoaDon_BanHang instance);
    partial void DeleteChiTiet_HoaDon_BanHang(ChiTiet_HoaDon_BanHang instance);
    partial void InsertHang_Hoa(Hang_Hoa instance);
    partial void UpdateHang_Hoa(Hang_Hoa instance);
    partial void DeleteHang_Hoa(Hang_Hoa instance);
    partial void InsertChiTiet_HoaDon_NhapHang(ChiTiet_HoaDon_NhapHang instance);
    partial void UpdateChiTiet_HoaDon_NhapHang(ChiTiet_HoaDon_NhapHang instance);
    partial void DeleteChiTiet_HoaDon_NhapHang(ChiTiet_HoaDon_NhapHang instance);
    partial void InsertHoaDon_BanHang(HoaDon_BanHang instance);
    partial void UpdateHoaDon_BanHang(HoaDon_BanHang instance);
    partial void DeleteHoaDon_BanHang(HoaDon_BanHang instance);
    partial void InsertKhach_Hang(Khach_Hang instance);
    partial void UpdateKhach_Hang(Khach_Hang instance);
    partial void DeleteKhach_Hang(Khach_Hang instance);
    partial void InsertHoaDon_Nhap(HoaDon_Nhap instance);
    partial void UpdateHoaDon_Nhap(HoaDon_Nhap instance);
    partial void DeleteHoaDon_Nhap(HoaDon_Nhap instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    #endregion
		
		public DataDiagramDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLSieuThiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDiagramDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDiagramDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDiagramDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDiagramDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTiet_HoaDon_BanHang> ChiTiet_HoaDon_BanHangs
		{
			get
			{
				return this.GetTable<ChiTiet_HoaDon_BanHang>();
			}
		}
		
		public System.Data.Linq.Table<Hang_Hoa> Hang_Hoas
		{
			get
			{
				return this.GetTable<Hang_Hoa>();
			}
		}
		
		public System.Data.Linq.Table<ChiTiet_HoaDon_NhapHang> ChiTiet_HoaDon_NhapHangs
		{
			get
			{
				return this.GetTable<ChiTiet_HoaDon_NhapHang>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon_BanHang> HoaDon_BanHangs
		{
			get
			{
				return this.GetTable<HoaDon_BanHang>();
			}
		}
		
		public System.Data.Linq.Table<Khach_Hang> Khach_Hangs
		{
			get
			{
				return this.GetTable<Khach_Hang>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon_Nhap> HoaDon_Nhaps
		{
			get
			{
				return this.GetTable<HoaDon_Nhap>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet_HoaDon_BanHang")]
	public partial class ChiTiet_HoaDon_BanHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaHang;
		
		private System.Nullable<int> _SoLuongHang;
		
		private System.Nullable<int> _TongTienHang;
		
		private EntityRef<Hang_Hoa> _Hang_Hoa;
		
		private EntityRef<HoaDon_BanHang> _HoaDon_BanHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnSoLuongHangChanging(System.Nullable<int> value);
    partial void OnSoLuongHangChanged();
    partial void OnTongTienHangChanging(System.Nullable<int> value);
    partial void OnTongTienHangChanged();
    #endregion
		
		public ChiTiet_HoaDon_BanHang()
		{
			this._Hang_Hoa = default(EntityRef<Hang_Hoa>);
			this._HoaDon_BanHang = default(EntityRef<HoaDon_BanHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HoaDon_BanHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					if (this._Hang_Hoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongHang", DbType="Int")]
		public System.Nullable<int> SoLuongHang
		{
			get
			{
				return this._SoLuongHang;
			}
			set
			{
				if ((this._SoLuongHang != value))
				{
					this.OnSoLuongHangChanging(value);
					this.SendPropertyChanging();
					this._SoLuongHang = value;
					this.SendPropertyChanged("SoLuongHang");
					this.OnSoLuongHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienHang", DbType="Int")]
		public System.Nullable<int> TongTienHang
		{
			get
			{
				return this._TongTienHang;
			}
			set
			{
				if ((this._TongTienHang != value))
				{
					this.OnTongTienHangChanging(value);
					this.SendPropertyChanging();
					this._TongTienHang = value;
					this.SendPropertyChanged("TongTienHang");
					this.OnTongTienHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang_Hoa_ChiTiet_HoaDon_BanHang", Storage="_Hang_Hoa", ThisKey="MaHang", OtherKey="MaHang", IsForeignKey=true)]
		public Hang_Hoa Hang_Hoa
		{
			get
			{
				return this._Hang_Hoa.Entity;
			}
			set
			{
				Hang_Hoa previousValue = this._Hang_Hoa.Entity;
				if (((previousValue != value) 
							|| (this._Hang_Hoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hang_Hoa.Entity = null;
						previousValue.ChiTiet_HoaDon_BanHangs.Remove(this);
					}
					this._Hang_Hoa.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_HoaDon_BanHangs.Add(this);
						this._MaHang = value.MaHang;
					}
					else
					{
						this._MaHang = default(string);
					}
					this.SendPropertyChanged("Hang_Hoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_BanHang_ChiTiet_HoaDon_BanHang", Storage="_HoaDon_BanHang", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HoaDon_BanHang HoaDon_BanHang
		{
			get
			{
				return this._HoaDon_BanHang.Entity;
			}
			set
			{
				HoaDon_BanHang previousValue = this._HoaDon_BanHang.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon_BanHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon_BanHang.Entity = null;
						previousValue.ChiTiet_HoaDon_BanHangs.Remove(this);
					}
					this._HoaDon_BanHang.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_HoaDon_BanHangs.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("HoaDon_BanHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hang_Hoa")]
	public partial class Hang_Hoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHang;
		
		private string _TenHang;
		
		private string _MaNhaCungCap;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _SoLuong;
		
		private EntitySet<ChiTiet_HoaDon_BanHang> _ChiTiet_HoaDon_BanHangs;
		
		private EntitySet<ChiTiet_HoaDon_NhapHang> _ChiTiet_HoaDon_NhapHangs;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnMaNhaCungCapChanging(string value);
    partial void OnMaNhaCungCapChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public Hang_Hoa()
		{
			this._ChiTiet_HoaDon_BanHangs = new EntitySet<ChiTiet_HoaDon_BanHang>(new Action<ChiTiet_HoaDon_BanHang>(this.attach_ChiTiet_HoaDon_BanHangs), new Action<ChiTiet_HoaDon_BanHang>(this.detach_ChiTiet_HoaDon_BanHangs));
			this._ChiTiet_HoaDon_NhapHangs = new EntitySet<ChiTiet_HoaDon_NhapHang>(new Action<ChiTiet_HoaDon_NhapHang>(this.attach_ChiTiet_HoaDon_NhapHangs), new Action<ChiTiet_HoaDon_NhapHang>(this.detach_ChiTiet_HoaDon_NhapHangs));
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(50)")]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhaCungCap", DbType="NChar(10)")]
		public string MaNhaCungCap
		{
			get
			{
				return this._MaNhaCungCap;
			}
			set
			{
				if ((this._MaNhaCungCap != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._MaNhaCungCap = value;
					this.SendPropertyChanged("MaNhaCungCap");
					this.OnMaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang_Hoa_ChiTiet_HoaDon_BanHang", Storage="_ChiTiet_HoaDon_BanHangs", ThisKey="MaHang", OtherKey="MaHang")]
		public EntitySet<ChiTiet_HoaDon_BanHang> ChiTiet_HoaDon_BanHangs
		{
			get
			{
				return this._ChiTiet_HoaDon_BanHangs;
			}
			set
			{
				this._ChiTiet_HoaDon_BanHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang_Hoa_ChiTiet_HoaDon_NhapHang", Storage="_ChiTiet_HoaDon_NhapHangs", ThisKey="MaHang", OtherKey="MaHang")]
		public EntitySet<ChiTiet_HoaDon_NhapHang> ChiTiet_HoaDon_NhapHangs
		{
			get
			{
				return this._ChiTiet_HoaDon_NhapHangs;
			}
			set
			{
				this._ChiTiet_HoaDon_NhapHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Hang_Hoa", Storage="_NhaCungCap", ThisKey="MaNhaCungCap", OtherKey="MaNhaCungCap", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.Hang_Hoas.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.Hang_Hoas.Add(this);
						this._MaNhaCungCap = value.MaNhaCungCap;
					}
					else
					{
						this._MaNhaCungCap = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_HoaDon_BanHangs(ChiTiet_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.Hang_Hoa = this;
		}
		
		private void detach_ChiTiet_HoaDon_BanHangs(ChiTiet_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.Hang_Hoa = null;
		}
		
		private void attach_ChiTiet_HoaDon_NhapHangs(ChiTiet_HoaDon_NhapHang entity)
		{
			this.SendPropertyChanging();
			entity.Hang_Hoa = this;
		}
		
		private void detach_ChiTiet_HoaDon_NhapHangs(ChiTiet_HoaDon_NhapHang entity)
		{
			this.SendPropertyChanging();
			entity.Hang_Hoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet_HoaDon_NhapHang")]
	public partial class ChiTiet_HoaDon_NhapHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDonNhap;
		
		private string _MaHang;
		
		private string _MaNhaCungCap;
		
		private System.Nullable<int> _SoLuongHang;
		
		private System.Nullable<int> _TongTien;
		
		private EntityRef<Hang_Hoa> _Hang_Hoa;
		
		private EntityRef<HoaDon_Nhap> _HoaDon_Nhap;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonNhapChanging(string value);
    partial void OnMaHoaDonNhapChanged();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnMaNhaCungCapChanging(string value);
    partial void OnMaNhaCungCapChanged();
    partial void OnSoLuongHangChanging(System.Nullable<int> value);
    partial void OnSoLuongHangChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public ChiTiet_HoaDon_NhapHang()
		{
			this._Hang_Hoa = default(EntityRef<Hang_Hoa>);
			this._HoaDon_Nhap = default(EntityRef<HoaDon_Nhap>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDonNhap", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDonNhap
		{
			get
			{
				return this._MaHoaDonNhap;
			}
			set
			{
				if ((this._MaHoaDonNhap != value))
				{
					if (this._HoaDon_Nhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonNhapChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDonNhap = value;
					this.SendPropertyChanged("MaHoaDonNhap");
					this.OnMaHoaDonNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					if (this._Hang_Hoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhaCungCap", DbType="NChar(10)")]
		public string MaNhaCungCap
		{
			get
			{
				return this._MaNhaCungCap;
			}
			set
			{
				if ((this._MaNhaCungCap != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._MaNhaCungCap = value;
					this.SendPropertyChanged("MaNhaCungCap");
					this.OnMaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongHang", DbType="Int")]
		public System.Nullable<int> SoLuongHang
		{
			get
			{
				return this._SoLuongHang;
			}
			set
			{
				if ((this._SoLuongHang != value))
				{
					this.OnSoLuongHangChanging(value);
					this.SendPropertyChanging();
					this._SoLuongHang = value;
					this.SendPropertyChanged("SoLuongHang");
					this.OnSoLuongHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang_Hoa_ChiTiet_HoaDon_NhapHang", Storage="_Hang_Hoa", ThisKey="MaHang", OtherKey="MaHang", IsForeignKey=true)]
		public Hang_Hoa Hang_Hoa
		{
			get
			{
				return this._Hang_Hoa.Entity;
			}
			set
			{
				Hang_Hoa previousValue = this._Hang_Hoa.Entity;
				if (((previousValue != value) 
							|| (this._Hang_Hoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hang_Hoa.Entity = null;
						previousValue.ChiTiet_HoaDon_NhapHangs.Remove(this);
					}
					this._Hang_Hoa.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_HoaDon_NhapHangs.Add(this);
						this._MaHang = value.MaHang;
					}
					else
					{
						this._MaHang = default(string);
					}
					this.SendPropertyChanged("Hang_Hoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_Nhap_ChiTiet_HoaDon_NhapHang", Storage="_HoaDon_Nhap", ThisKey="MaHoaDonNhap", OtherKey="MaHoaDonNhap", IsForeignKey=true)]
		public HoaDon_Nhap HoaDon_Nhap
		{
			get
			{
				return this._HoaDon_Nhap.Entity;
			}
			set
			{
				HoaDon_Nhap previousValue = this._HoaDon_Nhap.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon_Nhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon_Nhap.Entity = null;
						previousValue.ChiTiet_HoaDon_NhapHangs.Remove(this);
					}
					this._HoaDon_Nhap.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_HoaDon_NhapHangs.Add(this);
						this._MaHoaDonNhap = value.MaHoaDonNhap;
					}
					else
					{
						this._MaHoaDonNhap = default(string);
					}
					this.SendPropertyChanged("HoaDon_Nhap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_ChiTiet_HoaDon_NhapHang", Storage="_NhaCungCap", ThisKey="MaNhaCungCap", OtherKey="MaNhaCungCap", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.ChiTiet_HoaDon_NhapHangs.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_HoaDon_NhapHangs.Add(this);
						this._MaNhaCungCap = value.MaNhaCungCap;
					}
					else
					{
						this._MaNhaCungCap = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon_BanHang")]
	public partial class HoaDon_BanHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private System.Nullable<System.DateTime> _NgayLapHoaDon;
		
		private string _MaKH;
		
		private System.Nullable<int> _TongTien;
		
		private string _MaNV;
		
		private EntitySet<ChiTiet_HoaDon_BanHang> _ChiTiet_HoaDon_BanHangs;
		
		private EntityRef<Khach_Hang> _Khach_Hang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnNgayLapHoaDonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapHoaDonChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public HoaDon_BanHang()
		{
			this._ChiTiet_HoaDon_BanHangs = new EntitySet<ChiTiet_HoaDon_BanHang>(new Action<ChiTiet_HoaDon_BanHang>(this.attach_ChiTiet_HoaDon_BanHangs), new Action<ChiTiet_HoaDon_BanHang>(this.detach_ChiTiet_HoaDon_BanHangs));
			this._Khach_Hang = default(EntityRef<Khach_Hang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapHoaDon", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapHoaDon
		{
			get
			{
				return this._NgayLapHoaDon;
			}
			set
			{
				if ((this._NgayLapHoaDon != value))
				{
					this.OnNgayLapHoaDonChanging(value);
					this.SendPropertyChanging();
					this._NgayLapHoaDon = value;
					this.SendPropertyChanged("NgayLapHoaDon");
					this.OnNgayLapHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._Khach_Hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_BanHang_ChiTiet_HoaDon_BanHang", Storage="_ChiTiet_HoaDon_BanHangs", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<ChiTiet_HoaDon_BanHang> ChiTiet_HoaDon_BanHangs
		{
			get
			{
				return this._ChiTiet_HoaDon_BanHangs;
			}
			set
			{
				this._ChiTiet_HoaDon_BanHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_Hang_HoaDon_BanHang", Storage="_Khach_Hang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public Khach_Hang Khach_Hang
		{
			get
			{
				return this._Khach_Hang.Entity;
			}
			set
			{
				Khach_Hang previousValue = this._Khach_Hang.Entity;
				if (((previousValue != value) 
							|| (this._Khach_Hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khach_Hang.Entity = null;
						previousValue.HoaDon_BanHangs.Remove(this);
					}
					this._Khach_Hang.Entity = value;
					if ((value != null))
					{
						value.HoaDon_BanHangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("Khach_Hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon_BanHang", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDon_BanHangs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDon_BanHangs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_HoaDon_BanHangs(ChiTiet_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon_BanHang = this;
		}
		
		private void detach_ChiTiet_HoaDon_BanHangs(ChiTiet_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon_BanHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khach_Hang")]
	public partial class Khach_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<HoaDon_BanHang> _HoaDon_BanHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public Khach_Hang()
		{
			this._HoaDon_BanHangs = new EntitySet<HoaDon_BanHang>(new Action<HoaDon_BanHang>(this.attach_HoaDon_BanHangs), new Action<HoaDon_BanHang>(this.detach_HoaDon_BanHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_Hang_HoaDon_BanHang", Storage="_HoaDon_BanHangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HoaDon_BanHang> HoaDon_BanHangs
		{
			get
			{
				return this._HoaDon_BanHangs;
			}
			set
			{
				this._HoaDon_BanHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDon_BanHangs(HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.Khach_Hang = this;
		}
		
		private void detach_HoaDon_BanHangs(HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.Khach_Hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon_Nhap")]
	public partial class HoaDon_Nhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDonNhap;
		
		private System.Nullable<System.DateTime> _NgayNhapHang;
		
		private string _DonViTinh;
		
		private System.Nullable<int> _TongTien;
		
		private string _MaNV;
		
		private EntitySet<ChiTiet_HoaDon_NhapHang> _ChiTiet_HoaDon_NhapHangs;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonNhapChanging(string value);
    partial void OnMaHoaDonNhapChanged();
    partial void OnNgayNhapHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapHangChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public HoaDon_Nhap()
		{
			this._ChiTiet_HoaDon_NhapHangs = new EntitySet<ChiTiet_HoaDon_NhapHang>(new Action<ChiTiet_HoaDon_NhapHang>(this.attach_ChiTiet_HoaDon_NhapHangs), new Action<ChiTiet_HoaDon_NhapHang>(this.detach_ChiTiet_HoaDon_NhapHangs));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDonNhap", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDonNhap
		{
			get
			{
				return this._MaHoaDonNhap;
			}
			set
			{
				if ((this._MaHoaDonNhap != value))
				{
					this.OnMaHoaDonNhapChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDonNhap = value;
					this.SendPropertyChanged("MaHoaDonNhap");
					this.OnMaHoaDonNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhapHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhapHang
		{
			get
			{
				return this._NgayNhapHang;
			}
			set
			{
				if ((this._NgayNhapHang != value))
				{
					this.OnNgayNhapHangChanging(value);
					this.SendPropertyChanging();
					this._NgayNhapHang = value;
					this.SendPropertyChanged("NgayNhapHang");
					this.OnNgayNhapHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_Nhap_ChiTiet_HoaDon_NhapHang", Storage="_ChiTiet_HoaDon_NhapHangs", ThisKey="MaHoaDonNhap", OtherKey="MaHoaDonNhap")]
		public EntitySet<ChiTiet_HoaDon_NhapHang> ChiTiet_HoaDon_NhapHangs
		{
			get
			{
				return this._ChiTiet_HoaDon_NhapHangs;
			}
			set
			{
				this._ChiTiet_HoaDon_NhapHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon_Nhap", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDon_Nhaps.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDon_Nhaps.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_HoaDon_NhapHangs(ChiTiet_HoaDon_NhapHang entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon_Nhap = this;
		}
		
		private void detach_ChiTiet_HoaDon_NhapHangs(ChiTiet_HoaDon_NhapHang entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon_Nhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhaCungCap;
		
		private string _TenNhaCungCap;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<Hang_Hoa> _Hang_Hoas;
		
		private EntitySet<ChiTiet_HoaDon_NhapHang> _ChiTiet_HoaDon_NhapHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhaCungCapChanging(string value);
    partial void OnMaNhaCungCapChanged();
    partial void OnTenNhaCungCapChanging(string value);
    partial void OnTenNhaCungCapChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._Hang_Hoas = new EntitySet<Hang_Hoa>(new Action<Hang_Hoa>(this.attach_Hang_Hoas), new Action<Hang_Hoa>(this.detach_Hang_Hoas));
			this._ChiTiet_HoaDon_NhapHangs = new EntitySet<ChiTiet_HoaDon_NhapHang>(new Action<ChiTiet_HoaDon_NhapHang>(this.attach_ChiTiet_HoaDon_NhapHangs), new Action<ChiTiet_HoaDon_NhapHang>(this.detach_ChiTiet_HoaDon_NhapHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhaCungCap", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhaCungCap
		{
			get
			{
				return this._MaNhaCungCap;
			}
			set
			{
				if ((this._MaNhaCungCap != value))
				{
					this.OnMaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._MaNhaCungCap = value;
					this.SendPropertyChanged("MaNhaCungCap");
					this.OnMaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhaCungCap", DbType="NVarChar(50)")]
		public string TenNhaCungCap
		{
			get
			{
				return this._TenNhaCungCap;
			}
			set
			{
				if ((this._TenNhaCungCap != value))
				{
					this.OnTenNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._TenNhaCungCap = value;
					this.SendPropertyChanged("TenNhaCungCap");
					this.OnTenNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Hang_Hoa", Storage="_Hang_Hoas", ThisKey="MaNhaCungCap", OtherKey="MaNhaCungCap")]
		public EntitySet<Hang_Hoa> Hang_Hoas
		{
			get
			{
				return this._Hang_Hoas;
			}
			set
			{
				this._Hang_Hoas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_ChiTiet_HoaDon_NhapHang", Storage="_ChiTiet_HoaDon_NhapHangs", ThisKey="MaNhaCungCap", OtherKey="MaNhaCungCap")]
		public EntitySet<ChiTiet_HoaDon_NhapHang> ChiTiet_HoaDon_NhapHangs
		{
			get
			{
				return this._ChiTiet_HoaDon_NhapHangs;
			}
			set
			{
				this._ChiTiet_HoaDon_NhapHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hang_Hoas(Hang_Hoa entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_Hang_Hoas(Hang_Hoa entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
		
		private void attach_ChiTiet_HoaDon_NhapHangs(ChiTiet_HoaDon_NhapHang entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_ChiTiet_HoaDon_NhapHangs(ChiTiet_HoaDon_NhapHang entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _ChucVu;
		
		private System.Nullable<int> _Luong;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private EntitySet<HoaDon_BanHang> _HoaDon_BanHangs;
		
		private EntitySet<HoaDon_Nhap> _HoaDon_Nhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnLuongChanging(System.Nullable<int> value);
    partial void OnLuongChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDon_BanHangs = new EntitySet<HoaDon_BanHang>(new Action<HoaDon_BanHang>(this.attach_HoaDon_BanHangs), new Action<HoaDon_BanHang>(this.detach_HoaDon_BanHangs));
			this._HoaDon_Nhaps = new EntitySet<HoaDon_Nhap>(new Action<HoaDon_Nhap>(this.attach_HoaDon_Nhaps), new Action<HoaDon_Nhap>(this.detach_HoaDon_Nhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Int")]
		public System.Nullable<int> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon_BanHang", Storage="_HoaDon_BanHangs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HoaDon_BanHang> HoaDon_BanHangs
		{
			get
			{
				return this._HoaDon_BanHangs;
			}
			set
			{
				this._HoaDon_BanHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon_Nhap", Storage="_HoaDon_Nhaps", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HoaDon_Nhap> HoaDon_Nhaps
		{
			get
			{
				return this._HoaDon_Nhaps;
			}
			set
			{
				this._HoaDon_Nhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDon_BanHangs(HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDon_BanHangs(HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HoaDon_Nhaps(HoaDon_Nhap entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDon_Nhaps(HoaDon_Nhap entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan
	{
		
		private string _username;
		
		private string _password;
		
		private string _name;
		
		private string _phone;
		
		private string _email;
		
		public TaiKhoan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(MAX)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
